
version: 2
jobs:
  build:
    docker:
      - image: openjdk:11
        working_directory: ~/repo
        environment:
          # Customize the JVM maximum heap limit
          JVM_OPTS: -Xmx3200m
          TERM: dumb
          SBT_VERSION: 1.3.8

      - image: circleci/postgres:12.2
        environment:
          POSTGRES_USER=cookbook
          POSTGRES_PASSWORD=cookbook



    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run:
          name: Get sbt binary
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -y python-pip git
            pip install awscli
            apt-get clean && apt-get autoclean
      - checkout
      # Download and cache dependencies
      - restore_cache:
          key: sbt-cache

      - run: cat /dev/null | sbt "Test / compile"

      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

      # run tests!
      - run: cat /dev/null | sbt test
      - store_test_results:
          path: boot/target/test-reports
